### ISSUE TITLE
Error: package google.golang.org/protobuf/proto is not a main package when running make

### ISSUE THREAD

**Issue by NikOkol** [mehdihadeli/go-food-delivery-microservices#107]
Description:

When attempting to set up the project using make, I encounter the following error:

package google.golang.org/protobuf/proto is not a main package
make: *** [install-tools] Error 1

Environment:

Operating System: MacOS
Go Version: go1.23.1 darwin/amd64

Steps to Reproduce:

1. Run make in the project directory.
1. Observe the error message mentioned above.

Expected Behavior:

The project should build successfully without encountering errors related to the package google.golang.org/protobuf/proto.

Additional Information:

Please let me know if there are any specific dependencies or configurations required for compatibility with the Go version mentioned or any other troubleshooting steps I should follow.

**Comment by mehdihadeli** [comment]
Hi, 
Thanks for the report.
Should work now with installing tools with `make install-tools`

**Comment by NikOkol** [comment]
> Hi, Thanks for the report. Should work now with installing tools with `make install-tools`

Hello, Thanks for your reply. But executing this command does not solve my problem. The same error occurs when executing `make install-tools`.

If you need more details about my system configuration, please let me know.

**Comment by mehdihadeli** [comment]
Hi,
Yes please.
I tested it inside [github codespace](https://codespaces.new/mehdihadeli/go-food-delivery-microservices) and Linux, and it works.
Maybe it is related to operating system
